const USER_INFO = "USER_INFO";
const LOGIN_TOKEN = "LOGIN_TOKEN";
const MENU_LIST = "MENU_LIST";

const DISTRICT_PROVINCE = "DISTRICT_PROVINCE";
const DISTRICT_COUNTY = "DISTRICT_COUNTY";
const DISTRICT_COUNTY_ID = "DISTRICT_COUNTY_ID";
const DISTRICT_CITY = "DISTRICT_CITY";
const DISTRICT_CITY_ID = "DISTRICT_CITY_ID";


const CHECK_TYPE_LIST = "CHECK_TYPE_LIST";

const COMPANY_LIST_LIST = "COMPANY_LIST_LIST";
const COMPANY_LIST_PAGE = "COMPANY_LIST_PAGE";

const CONTRAST_LIST_LIST = "CONTRAST_LIST_LIST";
const CONTRAST_LIST_PAGE = "CONTRAST_LIST_PAGE";

const SERVICE_LIST_LIST = "SERVICE_LIST_LIST";
const SERVICE_LIST_PAGE = "SERVICE_LIST_PAGE";



const CHANNEL_LIST_LIST = "CHANNEL_LIST_LIST";
const CHANNEL_LIST_PAGE = "CHANNEL_LIST_PAGE";

const MANAGER_LIST_LIST = "MANAGER_LIST_LIST";
const MANAGER_LIST_PAGE = "MANAGER_LIST_PAGE";

const SPEINDUSTRY_LIST_LIST = "SPEINDUSTRY_LIST_LIST";
const SPEINDUSTRY_LIST_PAGE = "SPEINDUSTRY_LIST_PAGE";

const RISKCHEMICAL_LIST_LIST = "RISKCHEMICAL_LIST_LIST";
const RISKCHEMICAL_LIST_PAGE = "RISKCHEMICAL_LIST_PAGE";

const SUPERVISE_LIST_LIST = "SUPERVISE_LIST_LIST";
const SUPERVISE_LIST_PAGE = "SUPERVISE_LIST_PAGE";

const CHECKTASK_LIST_LIST = "CHECKTASK_LIST_LIST";
const CHECKTASK_LIST_PAGE = "CHECKTASK_LIST_PAGE";



const BASE_SUPERVISE_LIST_LIST = "BASE_SUPERVISE_LIST_LIST";

export default {
	DISTRICT_PROVINCE,
	DISTRICT_CITY,
	DISTRICT_CITY_ID,
	DISTRICT_COUNTY,
	DISTRICT_COUNTY_ID,
	CHECK_TYPE_LIST,
	USER_INFO,
	LOGIN_TOKEN,
	COMPANY_LIST_LIST,
	COMPANY_LIST_PAGE,
	CONTRAST_LIST_LIST,
	CONTRAST_LIST_PAGE,
	SERVICE_LIST_LIST,
	SERVICE_LIST_PAGE,
	CHANNEL_LIST_LIST,
	CHANNEL_LIST_PAGE,
	MANAGER_LIST_LIST,
	MANAGER_LIST_PAGE,
	SPEINDUSTRY_LIST_LIST,
	SPEINDUSTRY_LIST_PAGE,
	RISKCHEMICAL_LIST_LIST,
	RISKCHEMICAL_LIST_PAGE,
	SUPERVISE_LIST_LIST,
	SUPERVISE_LIST_PAGE,
	CHECKTASK_LIST_LIST,
	CHECKTASK_LIST_PAGE,
	BASE_SUPERVISE_LIST_LIST

}
